### ISSUE TITLE
[功能请求] 允许用户选择使用哪一浏览器打开稍后读

### ISSUE THREAD

**Issue by XMB-7** [SettingDust/utools-simpread-read-later#1]
如题, 我是主用火狐辅用Edge, 因为在火狐上没有完整版的简悦. 所以如果能设置使用哪一浏览器打开稍后读, 对我会很方便. 感谢.

**Comment by SettingDust** [comment]
即将发布的 0.2.0 支持 url scheme，也许没有这个功能的考虑可能性了
https://ksria.com/simpread/docs/#/Sync?id=urlscheme

**Comment by SettingDust** [comment]
https://github.com/SettingDust/utools-simpread-read-later/commit/928c32e74bdd3a46c508d45c56591b4c420d082d
