### ISSUE TITLE
[功能请求] 新增设置, 允许优先打开外链(云盘文件), 其次内链(本地文件), 再次原始链接.

### ISSUE THREAD

**Issue by XMB-7** [SettingDust/utools-simpread-read-later#2]
或者单独设置, 是否优先打开外链(如果构建了知识库, 亦即开通了开放平台, 并把本地快照放入云盘中以供外部访问).
这样就能在查看稍后读的同时, 顺带复制一下外链地址, 用于分享给他人, 或者分享给其它设备.
如果能单独加一个功能, 直接复制某篇稍后读的外链, 那就更好不过了. 感谢.

**Comment by SettingDust** [comment]
即将发布的 0.2.0 支持 url scheme，也许没有这个功能的考虑可能性了
[ksria.com/simpread/docs/#/Sync?id=urlscheme](https://ksria.com/simpread/docs/#/Sync?id=urlscheme)

**Comment by SettingDust** [comment]
https://github.com/SettingDust/utools-simpread-read-later/commit/64ffb025d0e7d93afa31501efd10ee8abeae94cd
