### ISSUE TITLE
条目可以正确显示，但是点击无法跳转

### ISSUE THREAD

**Issue by TSUHA0** [SettingDust/utools-simpread-read-later#4]
![image](https://user-images.githubusercontent.com/26431743/231528561-eb496707-5ce3-46f1-beca-987b46db9b90.png)

![image](https://user-images.githubusercontent.com/26431743/231529726-d4449302-a29d-42f3-aba1-52ddd1d2e7f9.png)

http://localhost:7026/unread 界面是可以正常打开的，请问这是为什么

**Comment by SettingDust** [comment]
关了 URL scheme 试试？

**Comment by TSUHA0** [comment]
不好意思，我发现是我的火绒拦截了同时他免打扰模式没提醒我，我在另外一台机器上复现的时候发现火绒提醒了，因此我解决了问题，和您的代码没有关系，占用您的时间非常抱歉。
这是个非常好的插件。
